### ISSUE TITLE
New Deck Edit QA

### ISSUE THREAD

**Issue by StormWulf** [SalvationDevelopment/YGOPro-Salvation-Server#247]
--How to view the New Deck Edit--
(1) In either the launcher or the website, click the Deck Edit tab. Keep in mind that the website doesn't have saved decks.
(2) Ignore the pop-up Deck Edit and return to the launcher screen.
(3) Type deckedit. If done successfully, you'll see the deck edit screen appear.

Troubleshoot the deck edit and write all issues that should be resolved before releasing it. 

--Problems that I have experienced--
-Deck dropdown keeps going back to the top choice
-Searching for "Normal" and "Pendulum" doesn't exclude Effect Monsters
-cards seem a bit small for thumbnails"
-Fonts for the left search options are a tad small"
-[9:30:12 AM] Se7eN: noticed the options glitch out if you put the launcher at a certain size
-[9:31:12 AM] Se7eN: 1022x559 http://prntscr.com/8y67fp
				1254x759 http://prntscr.com/8y67q5
-Levels should display as 4* rather than ****

**Comment by StormWulf** [comment]
Needs TCG/OCG/Anime/etc labels for cards

**Comment by Zayelion** [comment]
fixed issue where moving between decks left cards from old decks.
