### ISSUE TITLE
Forum Based News System

### ISSUE THREAD

**Issue by Zayelion** [SalvationDevelopment/YGOPro-Salvation-Server#256]
[ ] Get an array of threads from a specific Invision forum
[ ] Send it as a JSON object to the launcher

**Comment by IrateGod** [comment]
Almost done, about to add some very minor fix.

**Comment by Zayelion** [comment]
Last night everything seemed ok minus some noticeable lag. Is it possible to pull from a different location by saving the file as we discussed?

**Comment by StormWulf** [comment]
Clicking on the title of a news post in the launcher opens the forum in the launcher rather than in the user's browser. This must be fixed to open the forum thread in the browser, because it otherwise makes the launcher unusable by hiding the launcher tabs.

**Comment by Zayelion** [comment]
The way I have it now it opens two tabs for some reason (in chrome)

**Comment by IrateGod** [comment]
JSON is being saved to the main server's manifest. Need to add a function to update news every ten or so minutes.

**Comment by ChibiChanNya** [comment]
This is fixed now, right? Should be removed from the list.

**Comment by Zayelion** [comment]
implemented updater.js to check forum every 10mins
