### ISSUE TITLE
On-going problems after deploying the latest rebase

### ISSUE THREAD

**Issue by StormWulf** [SalvationDevelopment/YGOPro-Salvation-Server#262]
Don't mention anything regarding the Deck Edit, since the web Deck Edit is almost ready. Feel free to mention other issues.

-Window sizing buttons are gone
-When clicking an on-going game in the gamelist to spectate, cards don't load up properly. Some games however will just close the window.
--http://i.imgur.com/NZQ1MST.png
--http://i.imgur.com/vptiINL.png
-It sometimes takes multiple tries to host a game (may or may not be resolved)
-Replays aren't working properly

**Comment by Zayelion** [comment]
@Iceygo just fyi.

**Comment by StormWulf** [comment]
Updating the ocgcore.dll helped fix a lot of problems, but now we have the problem of not being able to spectate duels in progress

**Comment by StormWulf** [comment]
-When clicking an on-going game in the gamelist to spectate, cards don't load up properly. Some games however will just close the window.
--http://i.imgur.com/NZQ1MST.png
--http://i.imgur.com/NZQ1MST.png
-It sometimes takes multiple tries to host a game

**Comment by StormWulf** [comment]
Replays are bugging out again
