### ISSUE TITLE
Ranking Microservice

### ISSUE THREAD

**Issue by Zayelion** [SalvationDevelopment/YGOPro-Salvation-Server#281]
Create a microservice that records the `experience` of a duelist where the ID of the user is their username,`experience` is a integer starting at 0, and after each duel increments.

**Comment by Zayelion** [comment]
Should track
- [ ] Experience : number of duels played total.
- [ ] Completed Duels : number of duels played to completion
- [ ] Rage Quits : Number of duels lost due to technical issues / quits
- [ ] Wins ever
- [ ] Loses ever
- [ ] Ties
- [ ] Elo score

**Comment by DeltaEscher** [comment]
I'll help. I'm new to the project, which file would user statistic tracking be under, or would it be a new file?

**Comment by Zayelion** [comment]
https://github.com/SalvationDevelopment/ygopro-olympus/blob/master/libs/database.js

**Comment by DeltaEscher** [comment]
Anything particular in the file I should be looking into first, or anything that needs to be added?

**Comment by Zayelion** [comment]
The olympus project is a collab between Percy's team Salv's team and Buttys to replace the aging checkmate server. Its handled and no further efforts are needed for it.

**Comment by DeltaEscher** [comment]
So then wouldn't the issue be closed?
