### ISSUE TITLE
Manual Mode Examples

### ISSUE THREAD

**Issue by Zayelion** [SalvationDevelopment/YGOPro-Salvation-Server#284]
Provide full examples for the following.
- hostDuel
- joinDuel

Explain how turn management is done and RPS if any.

**Comment by IrateGod** [comment]
Server starts running /libs/manualMode.js
Client connects to the server through Primus:
```
var manual = new Primus("ygopro.us:55542"),
    uid = generateRandomString(16),
    username = getUsername(),
    deckList = getDeckList();
manual.on("open", function () {
    manual.on("data", function (data) {
        console.log(data); // stub, usually you'd handle the data passed from the server here
    });
    setInterval(function () {
        manual.write({
            action: "heartBeat",
            uid: uid,
            username: username
        });
    }, 36000);
});
// host a duel
manual.write({
    action: "hostDuel",
    uid: uid,
    username: username,
    duelID: "newDuelName",
    hostOptions: {
        banList: "2016.4.1 (TCG)", // look up the lflist.conf file to see how this should look like
        database: "0-en-OCGTCG",
        deckList: parseYDK(deckList)
    }
});
```

To join the duel, another client would initiate the same connection through Primus (of course their UID and Username would be different, as well as their deck).

They'd now send following data through Primus:

```
manual.write({
    action: "joinDuel",
    uid: uid,
    username: username,
    duelID: "newDuelName", // this must match the duelID in the hosted duel
    hostOptions: {
        deckList: parseYDK(deckList)
    }
});
```

**Comment by IrateGod** [comment]
As per request an example of how the deckList should look like:

http://prntscr.com/aprfq2

**Comment by IrateGod** [comment]
Just remembered this issue.

RPS is not explicitly included. I'll add it soon. Turn management is very rudimentary: in a duelQuery, the client can send `QUERY_END_TURN` to end their turn. Changing phases can be done through following write command:

```
manual.write({
    action: "duelQuery",
    uid: uid,
    username: username,
    duelID: "newDuelName",
    duelQuery: QUERY_CHANGE_PHASE,
    phase: PHASE_CONSTANT // DRAW_PHASE, MAIN_PHASE_ONE, etc.
});
```

**Comment by Zayelion** [comment]
I need the examples to not have constance or function calls for documentation purposes, otherwise its no different than staring at the code.
