### ISSUE TITLE
Manual Mode Security

### ISSUE THREAD

**Issue by IrateGod** [SalvationDevelopment/YGOPro-Salvation-Server#285]
Since I am very concerned about security, I would like your feedback on this matter.

Right now, the manual mode requires the client to pass a `uid` property in order for the server to process the command. This property was originally generated by the client through a randomizing function. Details are regardless, but there does exist a very small likelihood of there being duplicate UIDs.

I could have the server generate a truly unique UID which the client would first request, for example:
```
manual.write({
    action: "requestUID",
    username: username
});
```

Pros for this solution:
- UID is guaranteed to be unique
- algorithm that generates it cannot be seen on the client-side

Cons:
- Additional work for the server
- One extra command for the client

I'd like to hear @Zayelion's opinion on this matter, but if you as reader have the proper knowledge, feel free to contribute anyway.

**Comment by Zayelion** [comment]
Few methods :

- socket's IP + a code it gives that is randomly generated.
- DN uses a 16 digit hex hash given by the user.
- socket is verified via the forum auth module and while that connection is active they are verified as a user on that IP address, this list can be loaded from the gamelist via the internal server request system. The socket stays verified through out the session and reconnection doesnt require re-verification.
