### ISSUE TITLE
Cards that need SQLs

### ISSUE THREAD

**Issue by StormWulf** [SalvationDevelopment/YGOPro-Salvation-Server#286]
**ID correctons**
- [ ] Celtic Guard of Noble Arms `100202002 --> 45531624`
- [ ] Choco Magician Girl `100200115 --> 7198399`

**MVP18**
- [x] Dimension Sphinx `100207023`
- [x] Dimension Mirage `100207025`
- [x] Cubic Karma `100207041`
- [x] Cubic Aura `100207042`
- [x] Cubic Reincarnation `100207043`
- [ ] Gate of the Magical Contract `100207020`
- [ ] Dimension Reflector `100207020`
- [x] Unearthing Destiny `100207022`
- [x] Cubic Mandala `100207044`
- [x] Cubic Combination `100207045`
- [x] Magician's Protection `100207028`
- [x] Final Geas `100207029`
- [x] Metalhold the Mobile Fortified Fortress `100207030`

**CPF1** 
- [x] Raidraptor - Napalm Dragonius `100206004`
- [x] Raidraptor - Blade Burner Falcon `100206005`
- [x] The Blazing Mars `100206007`
- [x] Scrum Force `100206020`

**Comment by Zayelion** [comment]
The Cubic cards need their set codes adjusted.
