### ISSUE TITLE
Deck Edit isn't friendly to users with smaller screen resolutions

### ISSUE THREAD

**Issue by StormWulf** [SalvationDevelopment/YGOPro-Salvation-Server#316]
Many users are required to zoom their screen to 90% in order to view the Deck Edit screen properly. It's annoying for the staff to tell users about this solution, and it scares away users that refuse to seek help on Discord. Either we need a message in the Deck Edit screen that tells users how to fix their screen, or make it adjust appropriately for smaller screen resolutions.

**Comment by Zayelion** [comment]
Need the screen resolutions to reproduce.
