### ISSUE TITLE
Deck Edit speed optimization

### ISSUE THREAD

**Issue by StormWulf** [SalvationDevelopment/YGOPro-Salvation-Server#320]
Many users have issues with the Deck Edit being irritatingly slow. I have also noticed that the Deck Edit will search as soon as a key in typed. If the Deck Edit only searched after the user clicked the `Search` button rather than automatically, this may help improve speed optimization.

**Comment by Zayelion** [comment]
https://github.com/SalvationDevelopment/YGOPro-Salvation-Server/commit/29ec0b9
