### ISSUE TITLE
Deck editor bypasses cards limits on drag&drop.

### ISSUE THREAD

**Issue by Boronsama** [SalvationDevelopment/YGOPro-Salvation-Server#334]
The card editor allows you to bypass rules when using drag & drop. 

![http://prnt.sc/eu8ben](http://prnt.sc/eu8ben)

**Comment by Boronsama** [comment]
#335 made a pull request with the fix.

**Comment by Zayelion** [comment]
Pull request are accepted, it has been merged. Thank you for finding and fixing this!
