### ISSUE TITLE
There's way too many buttons

### ISSUE THREAD

**Issue by DiabladeZat** [SalvationDevelopment/YGOPro-Salvation-Server#338]
- [x] Limit excavate to only being usable from the deck
- [x] Remove "Reveal Random card" from MD
- [x] Remove "To the bottom of the deck" when browsing the deck
- [x] Remove "Signal effect" from monsters when browsing the deck
- [x] Remove "Flip Face-Down" and "To defense" from monsters in the extra deck
- [ ] Figure out another method of working counters then remove them from cards on the field. Preferably place the option in the bottom bar.
- [x] Remove "View" from monsters that are not overlay'd
- [ ] Remove "To opponent's hand" from cards on the field"
- [x] Remove "Flip Faceup" and "Activate" from face up S/T
- [x] Remove "To Defense" for cards in the Spell/Trap Zones
- [x] Remove "Special summon in defense" from S/T
- [x] Remove "To Monster Zone" from S/T
- [x] Remove "Face down" from Face down cards
- [x] Remove the option to put counters on Facedown Cards
- [ ] Consider renaming "SS in defense" to "Summon in Defense" and combining "Normal summon" and "SS in attack" into 1 button called "Summon in Attack" or giving SSing it's own new animation
- [x] Remove "To Extra Deck" from non-hybrid pendulums
- [x] Remove "Activate" from facedown S/T
- [x] Remove "flip Facedown" from spells and traps, already have "Flip Down"
- [x] Remove "Excavate from S/T" on the field. Your magical hats won't save you now!
- [x] Remove "Set in S/T" for Spell/Traps from the Deck, because all cards set directly from the deck to the field have to first reveal to the opponent before flipping facedown.

**Comment by DiabladeZat** [comment]
Also, remove "Activate" from facedown S/T

**Comment by DiabladeZat** [comment]
Found a few more.
1:Remove "Reveal bottom card" from deck
2:Remove " To extra deck" from all pendulums except ED pendulum hybrids.
3:Remove "To opponent's field" from cards in the hand
4: I still think the "Excavate" function is not needed.
5:Consider renaming "SS in defense" to "Summon in Defense" and combining "Normal summon" and "SS in attack" into 1 button called "Summon in Attack" or giving SSing it's own new animation

**Comment by DiabladeZat** [comment]
Also, Remove "To opponent's hand" from monsters on the field

**Comment by Zayelion** [comment]
Rejecting the following
> Remove "To opponent's hand" from cards on the field"

Kaiju being returned to hand after hitting

**Comment by Zayelion** [comment]
I set it so the remove counter only appears if there is already a counter on the card.
