### ISSUE TITLE
Deck database is case-sensitive for users

### ISSUE THREAD

**Issue by StormWulf** [SalvationDevelopment/YGOPro-Salvation-Server#349]
My account name is _StormWolf_, however I log in as _stormWolf_ (with the lowercasing), it appears to create a new array of decks because none of the ones from my account appear (it only shows the default _New Deck_, which is blank).

**Comment by ChibiChanNya** [comment]
Got em with latest commit (69c72f78b62943fd1b84432887ec804bebd97ac5). Please review!
