### ISSUE TITLE
Users are able to leave "dead games" without it erasing from the gamelist

### ISSUE THREAD

**Issue by StormWulf** [SalvationDevelopment/YGOPro-Salvation-Server#356]
There have been occurrences of a particular player listed in multiple games in the Gamelist. The only way that I am able to do this is if I open multiple tabs, but it's clear that this isn't the case. We need to investigate how users are able to leave an open game without their name being erased from it, as well as fix the issue.

**Comment by MorganLeFlaySD** [comment]
Switching to another tab during the formation of a duel allows their username to stick around in the game.
